version: 0.0
os: linux
files:
  - source: src/*
    destination: /entropyshift/codedeploy/overseer-ui/
hooks:
  ApplicationStop:
    - location: scripts/stop_application.sh
      timeout: 300
  ApplicationStart:
    - location: scripts/start_application.sh
      timeout: 300
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300