version: 0.1

environment_variables:
  plaintext:
    AUTHOR: "CHAITANYA_MEESALA"

phases:
  install:
    commands:
      - echo Install started on `date` 
  pre_build:
    commands:
      - echo Installing source NPM dependencies.
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the code with webpack
      - ./node_modules/.bin/webpack
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - src/*
    - scripts/*
    - package.json
    - appspec.yml
    - webpack.config.js
    - node_modules/*